version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: millerdb
    ports:
      - "5432:5432"
    volumes:
     - ./public/uploads:/app/public/uploads

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/millerdb?schema=public
      JWT_SECRET: MHMD96essam
      NEXT_PUBLIC_BASE_URL: http://localhost:3000

volumes:
  pg_data:
