version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecommerce
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
