version: '3.8'

services:
  app:
    build: .
    container_name: miller_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/millerdb
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  db:
    image: postgres:15
    container_name: miller_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: millerdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
